# Generated by Django 3.2.16 on 2022-11-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField()),
                ('x2', models.TextField()),
                ('x3', models.FloatField()),
                ('x4', models.FloatField()),
            ],
        ),
    ]
